### ISSUE TITLE
Seeing an thread that's unread, with no new activity

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3229]
![screen shot 2016-04-20 at 2 30 31 pm](https://cloud.githubusercontent.com/assets/750477/14661787/9a3ac022-0704-11e6-98a3-64988f06f40d.png)
![screen shot 2016-04-20 at 2 30 35 pm](https://cloud.githubusercontent.com/assets/750477/14661786/9a374712-0704-11e6-87be-9461c5a4d875.png)

**Comment by alannallama** [comment]
<img width="618" alt="screen shot 2016-04-26 at 2 24 06 pm" src="https://cloud.githubusercontent.com/assets/5498878/14804808/9f0a761e-0bba-11e6-84b8-c7c1f4694e6e.png">

Happening for me, too. Seems related to the "read items not disappearing from unread" issue.

**Comment by robguthrie** [comment]
Thanks. We're going to fix this after beta is removed.

**Comment by gdpelican** [comment]
This should be fixed in #3282

**Comment by alannallama** [comment]
@gdpelican this is still happening. Not sure if it's being handled on the other thread or this one should be reopened...

<img width="669" alt="screen shot 2016-06-03 at 9 54 43 am" src="https://cloud.githubusercontent.com/assets/5498878/15762368/797b5d08-2971-11e6-9069-eef0fc9225d5.png">

**Comment by alannallama** [comment]
After not happening for ages, this bug has resurfaced today @gdpelican

**Comment by gdpelican** [comment]
I've seen it intermittently as well. I dunno what it is.

**Comment by finalcircuit** [comment]
I had one thread that had been in my Unread for a couple of weeks despite no new activity. I posted a new comment to the thread and that cleared it from the list. I'm guessing the new comment reset the tracking for the thread.

**Comment by gdpelican** [comment]
This should now be fixed.
