### ISSUE TITLE
"Contact Loomio" not working on side bar

### ISSUE THREAD

**Issue by uportalis** [loomio/loomio#3534]
When I click "Contact Loomio" on the new side bar nothing happens on the user interface.

**Comment by gdpelican** [comment]
Hey @uportalis, I'm not quite able to reproduce this behaviour. Is it not working for you ever? Which browser / OS are you running? Are you able to see any errors in your console after clicking on 'Contact Loomio'?

**Comment by uportalis** [comment]
I'm using Firefox 46.0 on windows 7.
When I click on the "Contact Loomio" element in the side bar, Firefox just sends a POST to https://www.loomio.org/ahoy/events with this parameter:
`[{"id":"97662378-eb5c-4fd0-bee0-32cee3bd2935","name":"$click","properties":{"tag":"a","class":"sidebar__list-item-button md-button md-ink-ripple","page":"/dashboard","text":"Contact Loomio","href":""},"time":1469024974.619}]`

Your server just returns HTTP code 200.

**Comment by rdbartlett** [comment]
It's not working for me, in Chrome 51 on OSX.

When I hover over the Contact link, I can see it is just pointing to `https://www.loomio.org`. Clicking it doesn't do anything, apart from generating this console error:

![image](https://cloud.githubusercontent.com/assets/970124/17091880/8ef5f4aa-5292-11e6-9c42-a8ef397099f4.png)

Is there more any more detail I can sniff out?

**Comment by rdbartlett** [comment]
Wow, 27 minutes later, the contact form opened! 

Could this be a bug with the Intercom API?

**Comment by gdpelican** [comment]
It certainly does seem to be some sort of bug on Intercom's end. I'm going to send this bug report over to them to see if they can eludicate it.

**Comment by gdpelican** [comment]
After talking with the intercom guy, I did this: #3546 

I believe this should fix this, although I'm still talking to him about _why_ it worked intermittently.

**Comment by rdbartlett** [comment]
This is still not working for me on Chrome, though it is on Safari.

**Comment by rdbartlett** [comment]
What can I do to help debug? 

Sometimes I can see `https://api-ping.intercom.io/vjs/users/ping 422` in the console and clicking Contact is unresponsive. Sometimes I get no console errors, and when I click Contact, it takes me to the contact page, rather than opening the Intercom widget.

**Comment by rdbartlett** [comment]
In FF 47 I get no response when I click 'Contact', and nothing in the console.

**Comment by alannallama** [comment]
Adding another similar report to this....

I'm in Firefox 47.0.1 and I can interact with Intercom messages normally in my regular browser window (the intercom widget appears as expected). However, in a Private Browsing window, I don't get incoming intercom messages in the app, and if I click "contact" in the sidebar, it sends me to loomio.org/contact instead of popping up the intercom widget.

**Comment by rdbartlett** [comment]
I found a clue with @robguthrie!

![image](https://cloud.githubusercontent.com/assets/970124/17345735/a0d263aa-595b-11e6-98be-afb21076c026.png)

**Comment by gdpelican** [comment]
Do you reckon this got taken care of @robguthrie ?

**Comment by gdpelican** [comment]
Closing hastily. Let me know if there's still issues here.

**Comment by alannallama** [comment]
This bug is still affecting me

**Comment by robguthrie** [comment]
Alanna, It would be great to screenshare with you and look at this issue
today.

**Comment by alannallama** [comment]
I'm out most of today unfortunately... have you tried reproducing in
Firefox private browsing window?
