### ISSUE TITLE
{{time}} template is not using momentjs locales

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4349]
In client translations, some strings use the {{time}} template (closing in, closed, etc.). This time template can be displayed as relative time, instead of the timestamp, but the relative time is always in english (in or ago etc.)

It seems that [momentjs supports a lot of locales](https://momentjs.com/), but Loomio requires "moment" and not "moment-with-locales": for example, in French, Loomio displays "3 years ago" or "in 3 days" instead of "il y a 3 ans" or "dans 3 jours" as it should with locales.

Thanks to @uportalis and @swergas for pointing this out and in #3898.

**Comment by robguthrie** [comment]
Thanks for bringing this up. Should be fixed today.

**Comment by juliencarnot** [comment]
Just noticed that the user locale is not applied on notifications:
![i18nnotifs](https://user-images.githubusercontent.com/3848493/32490658-31330e0e-c3b4-11e7-856a-d5a6effa5d22.png)
It also seems that poll types in notifications are not translated.

**Comment by robguthrie** [comment]
Hrrmm I'm seeing it working for notifications:
![image](https://user-images.githubusercontent.com/486367/32574974-9b396df0-c537-11e7-80d0-8648fb3f6b62.png)

Can you raise a seperate issue for the poll_type translations?

**Comment by juliencarnot** [comment]
Yep, I've seen momentjs strings in French today, and now it's back to english. I guess extreme language switching and caches do not mix well! ;-) 

opened https://github.com/loomio/loomio/issues/4401 for poll type.

**Comment by robguthrie** [comment]
that's really weird!!! I don't think caching has much to do with it, as each locale file has it's own url.
I'll run under another language for a while and see if they switch back.

**Comment by robguthrie** [comment]
are you still seeing this problem?

**Comment by juliencarnot** [comment]
Yes, it's still the case, only in the notification tray:
![daysago in fr](https://user-images.githubusercontent.com/3848493/32772490-4c429e9a-c926-11e7-82ef-669deda59590.png)

And the rest of the page gets the translations for moments, as it loads the fr moments locale:
![moments locales fr](https://user-images.githubusercontent.com/3848493/32772705-f9bd1316-c926-11e7-972c-12920c42a60e.png)

**Comment by juliencarnot** [comment]
Hum, not sure this is related to the notification problem, but I noticed in Chromium I had fr-fr then fr as preferred languages, and in that case, it throws a 404 error:
![momentsfr-fr](https://user-images.githubusercontent.com/3848493/32847565-9f2096d0-ca2a-11e7-8a44-69ff8f03e358.png)

if I switch to fr then fr-fr as preferred languages, no error.

**Comment by juliencarnot** [comment]
@robguthrie I'm still reproducing the issue. Can we reopen the issue?

**Comment by robguthrie** [comment]
I've looked into this and it's the intended momentjs behaviour from version 2.8.1 onwards, they say they're going to bring back a way to support the old behaviour but it does look like like one exists yet.

https://github.com/moment/moment/issues/1797

It's pretty lame, I think the fix for us is to use a single moment instance throughout the app. Gah.

**Comment by gdpelican** [comment]
This should now be fixed.

**Comment by juliencarnot** [comment]
I still have the times in the notification in English when using Loomio in French. Is this linked to the current rollback?

**Comment by juliencarnot** [comment]
![image](https://user-images.githubusercontent.com/3848493/36020769-0e90638c-0d84-11e8-97ee-955645accc0d.png)
I'm still having the issue, even in new notifications...
