### ISSUE TITLE
Markdown quotes not working

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#5303]
Writing a new post, I used `>` to delineate a quote. Checked the preview, looked fine. Pressed publish, and it looked like this:

![image](https://user-images.githubusercontent.com/970124/55399900-52650500-5544-11e9-913c-6e41f284c918.png)

The `>`'s have been replaced with `&gt;`s

**Comment by robguthrie** [comment]
fixed. ty

**Comment by rybesh** [comment]
This is still not working for me in Loomio 2.6.2. Same exact issue as original poster.

**Comment by robguthrie** [comment]
That image did not age well.
@rybesh are you using markdown or rich text mode mode? I'm not having a problem

https://user-images.githubusercontent.com/486367/105920004-77bcee80-609b-11eb-903d-568af2f5eb53.mov

**Comment by rybesh** [comment]
In your screen recording, aren't you in rich text (WYSIWYG) mode? I thought the M button on the far right switched you into Markdown mode (no buttons), which is what I typically use. When I'm in that mode, all the Markdown syntax seems to work *except* blockquote.


https://user-images.githubusercontent.com/84592/105922613-f6b51700-6008-11eb-9301-3bef78ca78b2.mov
