### ISSUE TITLE
Move items bug

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#6744]
I've selected some items, and now I want to choose a thread to move them to, but no threads turn up when I try to search for them:

![image](https://user-images.githubusercontent.com/1380991/87277124-cf4ba080-c535-11ea-83aa-411578c7e9d5.png)

**Comment by gregorykan** [comment]
Hey @mhjb 

At the moment you can only move items to threads that you've authored. I thought I'd revised this (so that you can move items to any thready you're a member of) but the constraint remains on the backend. I will look into rectifying this today!

**Comment by mhjb** [comment]
Thanks Greg. I though it wasn't coming up with any results at all — but I see it is coming up with other threads when I search, but quite slowly and with no visual indication that it's busy searching.

**Comment by gregorykan** [comment]
@mhjb ok i'm mistaken about the scope. it should actually be able to pull up any thread from any group you're a member of. would you mind verifying this for me?

perhaps the issue is the UI and lack of a loading indicator

**Comment by gregorykan** [comment]
have added a loading indicator now!

**Comment by mhjb** [comment]
Ah — some extra information: I'm in the discussion 2s6SRFfh (in a subgroup)
and I want to move some comments to BWAz9qZf (in the parent group). I'm an
admin of both subgroup and group.

**Comment by gregorykan** [comment]
hi again matthew! so just to confirm, you're saying that the destination thread you want isn't appearing in the autocomplete?

**Comment by mhjb** [comment]
That's right

**Comment by robguthrie** [comment]
Hi Matthew, we're not able to reproduce the problem here.

When we select the parent group, then search for "WCC", the thread shows up and the items we moved successfully appreared in the destination.

(done on a copy of production db)
<img width="648" alt="image" src="https://user-images.githubusercontent.com/486367/87887044-a4050c00-ca75-11ea-9b2b-c1599e307d4e.png">

Any other info, is the problem still happening for you?

**Comment by mhjb** [comment]
Thanks for your efforts! Alas still happening. I'll just leave the comments where they are :)

**Comment by robguthrie** [comment]
Sorry to bug you, are you able to make a screencast of what you're doing? I
don't really like leaving bugs in the app!

**Comment by mhjb** [comment]
An excellent attitude :). I'll email you the recording now.
