### ISSUE TITLE
Permission issues after 2.15.0 release

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#9059]
@robguthrie After we updated to 2.15.0 we found 2 permission issues:

- ~~a group admin user cannot edit other users polls, only their threads. For example: User A created poll X and Thread Y, User B is admin and can edit Y but not X.~~ UPDATE: this is working as expected, the user was not an admin in the group. After promoting him it worked, sorry for the noise.
- the Matrix notification bot is not available for all the users in the group. Before the release any user could use the Remind button to notify undecided users in matrix, now they can't. This is the error seen in the console to the GET request to `api/v1/chatbots?group_id=1`:

```javascript
Uncaught (in promise)
Object { exception: "CanCan::AccessDenied You are not authorized to access this page.", status: 403, statusText: "Forbidden", ok: false, … }
​
**sentry\_captured**: true
​
exception: "CanCan::AccessDenied You are not authorized to access this page."
​
ok: false
​
status: 403
​
statusText: "Forbidden"
```

I'm not sure if this is related to https://github.com/loomio/loomio/issues/9058

**Comment by robguthrie** [comment]
Sorry for the unexpected changes, and thank you for taking the time to
report the issues. I'll fix these tomorrow :)

**Comment by robguthrie** [comment]
Still working on this

**Comment by anarute** [comment]
hi @robguthrie! Any update on this one? Thank you 🙏

**Comment by robguthrie** [comment]
Thanks for the reminder @anarute - this should be fixed in the recently released: v2.15.2

**Comment by anarute** [comment]
It seems that there's a bug in the logic to show the Remind button that was preventing it from be displayed:

```diff
diff --git a/vue/src/shared/services/ability_service.coffee b/vue/src/shared/services/ability_service.coffee
index ab94fbac2..377355e89 100644
--- a/vue/src/shared/services/ability_service.coffee
+++ b/vue/src/shared/services/ability_service.coffee
@@ -120,7 +120,7 @@ export default new class AbilityService
     return false if poll.discardedAt
     if poll.groupId
       poll.group().adminsInclude(user()) ||
-      (poll.group().membersCanAnnounce && poll.group.membersInclude((user())))
+      (poll.group().membersCanAnnounce && poll.group().membersInclude((user())))
     else
       poll.adminsInclude(user())
```

Fixing this shows the button again but I still get 403 when trying to remind using a chatbot:

![Screen Shot 2022-11-17 at 12 36 26](https://user-images.githubusercontent.com/333447/202436231-d28d8a86-a551-4e66-a3c7-04572597280f.png)

I reproduced this by trying to remind a poll in a group that has a chatbot set with a user that is not admin in this group.

**Comment by robguthrie** [comment]
Hi @anarute.

I've fixed this, and tested it with a member now. I'm sorry the first attempt was not tested properly. Going forward, I'll list the tests I've performed when I fix bugs.

The fix for this is is master. Do you find it helpful when I make new versions for each fix? Or do you work against master? Please let me know what works best for you.
